channels:
  - defaults
  - conda-forge
dependencies:
  - numpy=1.19.2
  - pip>=20.3.3
  - python=3.9
  - imagemagick=7.1.0_16
  - graphviz=2.40.1
  - pip:
      - matplotlib==3.4.3
      - lightkurve==2.0.11
      - celerite2==0.2.0
      - exoplanet==0.5.1
      - pymc3_ext==0.1.1
      - corner==2.2.1
      - legwork==0.1.6
      - graphviz==0.19.1